name: Continuous Integration

on:
  push:
    branches:
      - storyline
  pull_request:
    branches:
      - storyline

jobs:
  test-wand-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Configure Poetry
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies with Poetry
        run: |
          poetry config virtualenvs.create false
          poetry install

      - name: Run backend tests with coverage
        run: |
          poetry run pytest --cov=./service/backend --cov-report=xml ./service/backend/tests

      - name: Upload backend coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: true
