name: Continuous Integration

on:
  push:
    branches:
      - storyline
  pull_request:
    branches:
      - storyline

jobs:
  test-wand-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./service/backend/requirements.txt
          pip install pytest-cov httpx

      - name: Run backend tests with coverage
        run: |
          pytest --cov=./service/backend --cov-report=xml ./service/backend/tests

      - name: Upload backend coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: true

  test-wand-zero:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
